### ISSUE TITLE
wsgi-request-logger fails to pip install if pypandoc is already installed

### ISSUE THREAD

**Issue by ajk8** [pklaus/wsgi-request-logger#11]
I ran into an issue whereby I could not get `wsgi-request-logger` to install if `pypandoc` was already installed in my virtual environment (python 3.5).

### Expected behavior

The following should work:
```
$ pip install pypandoc
$ pip install wsgi-request-logger
```

### Actual behavior

Executing the above results in the following error:

```
Collecting wsgi-request-logger
  Using cached wsgi-request-logger-0.4.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/4m/k137dqwd7hzftnctvnys5fxmkk84cx/T/pip-build-tqs7ddm_/wsgi-request-logger/setup.py", line 13, in <module>
        LDESC = pypandoc.convert('README.md', 'rst')
      File "<VIRTUALENV_ROOT>/lib/python3.5/site-packages/pypandoc/__init__.py", line 66, in convert
        raise RuntimeError("Format missing, but need one (identified source as text as no "
    RuntimeError: Format missing, but need one (identified source as text as no file with that name was found).
```

### Possible fixes

1. Check for the existence of `README.md` before attempting to use `pypandoc`
2. Modify `setup.py` to catch a `RuntimeError` from the `pypandoc` block

**Comment by pklaus** [comment]
Thanks for reporting. This should now be fixed.
